### ISSUE TITLE
站6也發生煙霧偵器的觸發訊號會和門禁的觸發訊號會同時動作的狀況

### ISSUE THREAD

**Issue by ysl0130** [karateboy/DataLogger#44]

**Comment by karateboy** [comment]
第六站門禁沒有設定, 從4/1~ 4/8都沒有門禁的警告

**Comment by karateboy** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1067042/24849779/e35696d8-1dff-11e7-83bc-faa7db9f1a61.png)

**Comment by karateboy** [comment]
從警報紀錄看不出煙霧和門禁有同步的關係...
