### ISSUE TITLE
程式異常中斷無法自動開啟

### ISSUE THREAD

**Issue by a1251chu** [karateboy/DataLogger#55]
因目前程式有設計當程式已開啟時會產生一個檔案避免重複開啟，但當程式是異常中斷時此檔案還是存在，故在恢復後無法自動開啟，是否可改成其他方式解決，以避免異常中斷(可能是斷電)之後還是可以自動開啟程式

**Comment by karateboy** [comment]
台積電和環保署測站都已修正
