### ISSUE TITLE
台積電的程式開啟後會有command line視窗

### ISSUE THREAD

**Issue by a1251chu** [karateboy/DataLogger#56]
![image](https://cloud.githubusercontent.com/assets/16241115/25928147/19e9e160-362d-11e7-988b-22b9be44e2d0.png)
台積電的程式開啟後會有一個command line視窗，為避免被人為關掉，需更新為沒有command line的版本

**Comment by karateboy** [comment]
已修正

**Comment by karateboy** [comment]
驗證後請關閉
