### ISSUE TITLE
加入GPS訊號

### ISSUE THREAD

**Issue by a1251chu** [karateboy/DataLogger#71]
已購買GPS並可用超級終端機連線收到資訊
資訊如下
$GPGGA,,,,,,0,00,,,M,0.0,M,,0000*48
$GPGLL,,,,,,V,N*64
$GPRMC,,V,,,,,,,,,,N*53
$GPVTG,,T,,M,,N,,K,N*2C
$GPGGA,,,,,,0,00,,,M,0.0,M,,0000*48
$GPGLL,,,,,,V,N*64
$GPGSA,A,1,,,,,,,,,,,,,,,*1E
$GPGSV,3,1,12,01,00,000,,02,00,000,,03,00,000,,04,00,000,*7C
$GPGSV,3,2,12,05,00,000,,06,00,000,,07,00,000,,08,00,000,*77
$GPGSV,3,3,12,09,00,000,,10,00,000,,11,00,000,,12,00,000,*71
$GPRMC,,V,,,,,,,,,,N*53
$GPVTG,,T,,M,,N,,K,N*2C
$GPGGA,,,,,,0,00,,,M,0.0,M,,0000*48
$GPGLL,,,,,,V,N*64
$GPRMC,,V,,,,,,,,,,N*53
$GPVTG,,T,,M,,N,,K,N*2C
$GPGGA,,,,,,0,00,,,M,0.0,M,,0000*48
$GPGLL,,,,,,V,N*64
$GPRMC,,V,,,,,,,,,,N*53
$GPVTG,,T,,M,,N,,K,N*2C
$GPGGA,,,,,,0,00,,,M,0.0,M,,0000*48

**Comment by karateboy** [comment]
請問這是EPA監測車, 還是台積電監測車要使用?

**Comment by a1251chu** [comment]
台積電的監測車，YS說合約好像有提到要有GPS

**Comment by karateboy** [comment]
已經支援
