### ISSUE TITLE
富貴角THC訊號中斷

### ISSUE THREAD

**Issue by victorcheng1972** [karateboy/DataLogger#73]
富貴角站於7/13 16：45 DAS系統停止運行，17：00 DAS系統重啟(疑似電腦重啟)，於17：18 後THC就失去連線。
7/14 09：25於DAS重新設定THC才又恢復連線。相關LOG如下：

[20170713富貴角log.txt](https://github.com/karateboy/DataLogger/files/1147271/20170713.log.txt)

**Comment by karateboy** [comment]
16:45 DAS收到程式結束的訊號 (正常關機/重啟)
> 2017-07-13 16:45:44,785 [ERROR] from application in ForkJoinPool-2-worker-3 - Closed
java.io.IOException: Closed

16:50 程式正常啟動
>2017-07-13 16:50:52,975 [INFO] from application in main - Application has started

之後MODBUS就無法連線到儀器 (應該TAPI的機器, 非THC) 

THC的儀器比較麻煩, 因為是UDP, 所以DAS和儀器間沒有連線....只知道送出UDP指令後, 儀器沒有回應.

**Comment by victorcheng1972** [comment]
了解，看來是暑內的人員安裝了什麼程式所造成的，因為原本都是正常運作的。感謝協助。
